FROM steamcmd/steamcmd:latest

EXPOSE 2001/udp
EXPOSE 17777/udp
EXPOSE 19999/udp


RUN apt update && \
    apt install -y --no-install-recommends libc6 libgcc-s1 libstdc++6 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p \
      /server/custom \
      /server/custom/addons \
      /server/custom/logs \
      /server/custom/profile \
      /server/custom/temp && \
    steamcmd +force_install_dir /server +login anonymous +app_update 1874900 validate +quit

COPY ./config/config.json /server/config.json

WORKDIR /server
ENTRYPOINT ["./ArmaReforgerServer"]
CMD ["-addonsDir", "./custom/addons", "-addonDownloadDir", "./custom", "-addonTempDir", "./custom/temp", "-autoreload", "10", "-config", "./config.json", "-freezeCheck", "300", "-logsDir", "./custom/logs", "-logLevel", "normal", "-logStats", "10000", "-logTime", "datetime", "-maxFPS", "120", "-profile", "./custom", "-backendLog", "-loadSessionSave", "-noThrow"]
