name: "Build and Push Docker Image to Dockerhub"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * 1"  # every Monday at 06:00 UTC
  workflow_dispatch: { }

jobs:
  push_to_registry:
    name: "Build and Push Docker Image"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Log in to DockerHub"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          push: "true"
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/reforger-image:latest"
          cache-from: "type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/reforger-image:cache"
          cache-to: "type=inline"

      - name: "Update Docker Hub Description"
        uses: "peter-evans/dockerhub-description@v3"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
          repository: "${{ secrets.DOCKERHUB_USERNAME }}/reforger-image"
          readme-filepath: "README.md"
          short-description: "Arma Reforger Dedicated Server (Docker)"
